Add 1.4.0 to changelog
JetBrains/compose-multiplatform pull request #3036
Opened 2023-04-11 15:18 UTC by MatkovIvan

2023-04-11 15:29 UTC, m-sasha commented
All the scrollbar fixes are missing:
- https://github.com/JetBrains/compose-multiplatform-core/pull/362
- https://github.com/JetBrains/compose-multiplatform-core/pull/365
- https://github.com/JetBrains/compose-multiplatform-core/pull/366
- https://github.com/JetBrains/compose-multiplatform-core/pull/372
- https://github.com/JetBrains/compose-multiplatform-core/pull/384
- https://github.com/JetBrains/compose-multiplatform-core/pull/387
- https://github.com/JetBrains/compose-multiplatform-core/pull/409

These can be summarized as

### Major Scrollbar overhaul
- Scrollbar now works correctly in lazy lists when items vary in size.
- Scrollbar now works correctly with lazy list contentPadding.
- Scrollbar now works correctly if the size of the scrollbar doesn't match the size of the widget it scrolls.
- Pressing the scrollbar track now works correctly.
- Added scrollbar support for lazy grid and text field.

2023-04-11 15:40 UTC, igordmn commented on CHANGELOG.md
> +- Update skiko from `0.7.54` to `0.7.58`
```suggestion
```
We usually don't mention skiko, just features from it.

2023-04-11 15:40 UTC, igordmn commented on CHANGELOG.md
> +- [Migrate skia to `m110`](https://github.com/JetBrains/skiko/pull/667)
```suggestion
```
Skia we don't mention as well

2023-04-11 15:40 UTC, igordmn commented on CHANGELOG.md
> +- [Support `painterResource` function common source set](https://github.com/JetBrains/compose-multiplatform/pull/2793)
```suggestion
- [Support `painterResource` function in common source set](https://github.com/JetBrains/compose-multiplatform/pull/2793)
```

2023-04-11 15:40 UTC, igordmn commented on CHANGELOG.md
> +- [Fix performing `ComposeScene.sendKeyEvent` an unintentional non-local return](https://github.com/JetBrains/compose-multiplatform-core/pull/398)
```suggestion
```
It is an internal fix

2023-04-11 15:40 UTC, igordmn commented on CHANGELOG.md
> +- [Fix crash `SplitPane` with a modifier](https://github.com/JetBrains/compose-multiplatform/issues/2214)
SplitPane is available only for desktop. Let's move it there

2023-04-11 15:40 UTC, igordmn commented on CHANGELOG.md
> +- [`compose.web` is renamed to `compose.html`](https://github.com/JetBrains/compose-multiplatform/pull/2997)
```suggestion
- [`Compose for Web` is renamed to `Compose HTML Library`](https://github.com/JetBrains/compose-multiplatform/pull/2997)
```

2023-04-11 15:42 UTC, m-sasha commented
[Fix window-sizing with `WindowState(size=Dp.Unspecified, undecorated=true, resizable=true)`](https://github.com/JetBrains/compose-multiplatform/issues/2676) is missing too.

2023-04-11 15:43 UTC, igordmn commented on CHANGELOG.md
> +- [`compose.web` is renamed to `compose.html`](https://github.com/JetBrains/compose-multiplatform/pull/2997)
Also, we should add:
- [The new experimental `Compose for Web` based on Kotlin/Wasm is available](README.md#web)

2023-04-11 15:44 UTC, m-sasha requested changes

2023-04-11 15:44 UTC, m-sasha commented on CHANGELOG.md
> +- [Fix `AlertDialog` shadow size](https://github.com/JetBrains/compose-multiplatform/issues/2857)
This fixes a bug introduced by another PR in the same version, so no need to mention it.

2023-04-11 15:48 UTC, MatkovIvan commented on CHANGELOG.md
> +- [Fix performing `ComposeScene.sendKeyEvent` an unintentional non-local return](https://github.com/JetBrains/compose-multiplatform-core/pull/398)
Already removed from previous feedback

2023-04-11 16:01 UTC, MatkovIvan commented
> All the scrollbar fixes are missing

> https://github.com/JetBrains/compose-multiplatform/issues/2676 is missing too.

The mentioned fixes were included in `1.3.1`

2023-04-11 16:05 UTC, igordmn approved these changes

2023-04-12 08:18 UTC, m-sasha approved these changes

2023-04-12 08:18 UTC, m-sasha commented on CHANGELOG.md
> +  - Scrollbar now works correctly in lazy list with spacing between items
https://github.com/JetBrains/compose-multiplatform-core/pull/380

2023-04-12 08:18 UTC, m-sasha commented on CHANGELOG.md
> +  - Scrollbar now works correctly if the size of the scrollbar doesn't match the size of the widget it scrolls
https://github.com/JetBrains/compose-multiplatform-core/pull/368

2023-04-12 09:12 UTC, MatkovIvan commented on CHANGELOG.md
> +  - Scrollbar now works correctly if the size of the scrollbar doesn't match the size of the widget it scrolls
```suggestion
  - [Scrollbar now works correctly if the size of the scrollbar doesn't match the size of the widget it scrolls](https://github.com/JetBrains/compose-multiplatform-core/pull/368)
```

2023-04-12 09:13 UTC, merged