Simplify resource management for iOS
JetBrains/compose-multiplatform pull request #3340
Opened 2023-07-11 14:37 UTC by AlexeyTsvetkov

Introduces a new task 'sync<FRAMEWORK_CLASSIFIER>ComposeIosResources', which collects resources from all source sets, included in iOS targets.

Now, CocoaPods integration does not require any configuration or calling 'pod install' after changing resources. * Important: existing projects need to remove 'extraSpecAttributes["resources"] = ...' from build scripts, and rerun `./gradlew podInstall` once!
Regular static frameworks should also just work.
Regular dynamic frameworks were not tested.
Currently, the task only copies resources from the module, which exports the framework.

Resolves:
 - #3073
 - #3113
 - #3066

2023-07-14 11:55 UTC, pjBooms commented
+ restructure sources in the way that resource management logic will be in a separate package

2023-07-14 12:45 UTC, pjBooms requested changes

2023-07-14 12:45 UTC, pjBooms commented on benchmarks/ios/animation-from-template/shared/build.gradle.kts
> -        extraSpecAttributes["resources"] = "['src/commonMain/resources/**', 'src/iosMain/resources/**']"
The changes in the samples and in the benchmarks should not be a part of this commit until we have a stable compose build that contains new resource management logic. We may create a separate PR for them that will be merged once we have such a version. And I would recommend to migrate all of them to regular framework and add a separate sample with CocoaPods usage.

2023-07-14 12:45 UTC, pjBooms commented on components/resources/library/src/iosMain/kotlin/org/jetbrains/compose/resources/Resource.ios.kt
> -        val absolutePath = NSBundle.mainBundle.resourcePath + "/" + path
We have a demo project https://github.com/JetBrains/compose-multiplatform/tree/master/components/resources/demo that is used to test the functionality. It should be synchronized with the changes in the library. So we need to migrate iOS part of the demo to new functionality for this and test it with locally build. When a dev build is available (after merge of this PR) it is better to update compose version to a dev build of the project.

2023-07-14 14:49 UTC, dima-avdeev-jb approved these changes
Checked in this branch: https://github.com/JetBrains/compose-multiplatform/pull/3351
Thanks, it works!!!

2023-07-18 11:27 UTC, pjBooms commented on components/gradle.properties
> +compose.version=0.0.0-dev1099
Change this to beta release version after release

2023-07-18 11:44 UTC, pjBooms requested changes

2023-07-18 11:44 UTC, pjBooms commented on gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/experimental/uikit/tasks/SyncComposeResourcesForIosTask.kt
> +        val outputDir = outputDir.get().asFile.apply { mkdirs() }
we need to clean the directory before copying to avoid copying resources that do not exist anymore

2023-07-18 17:11 UTC, merged