Added performance issue template
JetBrains/compose-multiplatform pull request #3415
Opened 2023-07-26 18:30 UTC by etolstoy

In order to collect more performance problems from Compose users, I'm adding a new issue template. We'll link to it from 1.5.0-Beta blogpost and other marketing materials.

2023-07-26 18:40 UTC, pjBooms commented on .github/ISSUE_TEMPLATE/performance.md
> +Please provide any relevant profiling data that might be helpful. This could include information like memory usage, CPU time, or any other data that could provide insight into the performance issue.
Mention please FPS here

2023-07-27 09:27 UTC, pjBooms requested changes
FPS metric should be explicitly mentioned as it is the main metric for UI performance

2023-07-27 16:58 UTC, etolstoy commented on .github/ISSUE_TEMPLATE/performance.md
> +Please provide any relevant profiling data that might be helpful. This could include information like memory usage, CPU time, or any other data that could provide insight into the performance issue.
Done

2023-07-27 20:57 UTC, pjBooms approved these changes

2023-07-28 13:02 UTC, igordmn approved these changes

2023-07-28 13:06 UTC, merged