Resources gradle plugin
JetBrains/compose-multiplatform pull request #3961
Opened 2023-11-21 11:21 UTC by terrakok

2023-11-21 15:38 UTC, dima-avdeev-jb commented
I don't know whym but CI fails. Error:
`org.gradle.testkit.runner.UnexpectedBuildFailure at KotlinCompatibilityTest.kt:45`

2023-11-21 16:02 UTC, dima-avdeev-jb reviewed
Type safe resource classes looks good!

2023-11-22 13:03 UTC, terrakok commented on components/resources/library/src/commonMain/kotlin/org/jetbrains/compose/resources/Resource.kt
> +    //TODO
Here will be a logic hot to select a concrete file by an environment and qualifiers

2023-11-22 14:26 UTC, dima-avdeev-jb approved these changes

2023-11-27 13:49 UTC, pjBooms requested changes

2023-11-27 13:49 UTC, pjBooms commented on gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/desktop/application/internal/ComposeProjectProperties.kt
> +    fun generateResourcesCertainly(providers: ProviderFactory): Provider<Boolean> =
generateResourcesCertainly->alwaysGenerateResourceAccessor
and the like (GENERATE_RESOURCES_CERTAINLY)

2023-11-27 13:49 UTC, pjBooms commented on gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/resources/GenerateResClassTask.kt
> +            val resources: Map<ResourceType, Map<String, List<ResourceItem>>> = dirs
I would add some unit-tests for this logic

2023-11-27 15:52 UTC, terrakok commented on components/resources/library/src/commonMain/kotlin/org/jetbrains/compose/resources/Resource.kt
> + *
Will be added later together with the qualifiers logic

2023-11-30 19:45 UTC, terrakok commented on gradle-plugins/compose/src/test/test-projects/misc/commonResources/expected/Res.kt
> +                ResourceItem(setOf(), "composeRes/images/vector.xml"),
Qualifiers are not implemented yet. It will be done in the next task

2023-12-01 11:24 UTC, terrakok commented on gradle-plugins/compose/src/test/test-projects/misc/commonResources/expected/Res.kt
> +                ResourceItem(setOf(), "composeRes/images/vector.xml"),
Added a few qualifiers to check the accessor generation

2023-12-01 14:38 UTC, merged