[resources] Use value classes for resource qualifiers.
JetBrains/compose-multiplatform pull request #4892
Opened 2024-05-29 09:21 UTC by terrakok

To reduce memory overhead a bit I changed data classes to value classes for resource qualifiers.

2024-05-29 17:11 UTC, igordmn requested changes

2024-05-29 17:22 UTC, igordmn commented on components/resources/library/api/library.klib.api
> -final const val org.jetbrains.compose.resources/org_jetbrains_compose_resources_LanguageQualifier$stableprop // org.jetbrains.compose.resources/org_jetbrains_compose_resources_LanguageQualifier$stabl
To solve this, we should add something like

```
// LanguageQualifierDeprecated.kt
@file:JvmName("LanguageQualifier")

@JsName("LanguageQualifier")
@Deprecated(level = HIDDEN)
data class LanguageQualifierDeprecated
```

Not sure what we should use for Native. We can break it in iOS Beta, but we should figure this out by iOS Release.

2024-05-30 10:50 UTC, terrakok commented on components/resources/library/api/library.klib.api
> -final const val org.jetbrains.compose.resources/org_jetbrains_compose_resources_LanguageQualifier$stableprop // org.jetbrains.compose.resources/org_jetbrains_compose_resources_LanguageQualifier$stabl
I agree. I changed it to regular classes to avoid data classes in semi-public API (it is internal API for the generated code)

2024-05-30 11:10 UTC, igordmn commented on components/resources/library/api/library.klib.api
> -final const val org.jetbrains.compose.resources/org_jetbrains_compose_resources_LanguageQualifier$stableprop // org.jetbrains.compose.resources/org_jetbrains_compose_resources_LanguageQualifier$stabl
Changing it to regular classes doesn't reduce memory overhead comparing to data classes. Though, getting rid of public data classes is also needed for future backward compatibility.

2024-05-30 12:45 UTC, igordmn approved these changes

2024-05-30 13:22 UTC, merged