[resources] Add image xml/svg bytearray converters to the corresponding source sets.
JetBrains/compose-multiplatform pull request #5098
Opened 2024-07-12 15:48 UTC by terrakok

The PR adds a method to convert a vector XML content bytearray to the ImageVector in the common code. And the same for an SVG files on non-android targets.

Fixes https://youtrack.jetbrains.com/issue/CMP-3869
Fixes https://youtrack.jetbrains.com/issue/CMP-4925

Fixes https://github.com/JetBrains/compose-multiplatform/issues/3869
Fixes https://github.com/JetBrains/compose-multiplatform/issues/4925

## Release Notes
### Features - Resources
- Added utility functions to decode `XML ByteArray as ImageVector` in the common code and `SVG ByteArray as Painter` in the non-android code

2024-07-18 14:54 UTC, igordmn requested changes

2024-07-18 14:54 UTC, igordmn commented on components/resources/library/src/commonMain/kotlin/org/jetbrains/compose/resources/ImageDecoders.kt
> +fun ByteArray.decodeToImageVector(density: Density): ImageVector {
```suggestion
 * @param sourceDensity density to apply during converting the source units to the [ImageVector] units (px -> dp, dp -> px).
 * @return The converted ImageVector.
 */
@ExperimentalResourceApi
fun ByteArray.decodeToImageVector(sourceDensity: Density): ImageVector {
```

2024-07-18 14:54 UTC, igordmn commented on components/resources/library/src/skikoMain/kotlin/org/jetbrains/compose/resources/ImageDecoders.skiko.kt
> +fun ByteArray.decodeToSvgPainter(density: Density): Painter {
```suggestion
 * @param sourceDensity density to apply during converting the source units to the [Painter] units (px -> dp, dp -> px).
 * @return The converted Painter.
 */
@ExperimentalResourceApi
fun ByteArray.decodeToSvgPainter(sourceDensity: Density): Painter {
```

2024-07-18 14:57 UTC, igordmn commented
> Fixes https://github.com/JetBrains/compose-multiplatform/issues/3869
> Fixes https://github.com/JetBrains/compose-multiplatform/issues/4925

It doesn't fix it completely, until https://android-review.googlesource.com/c/platform/frameworks/support/+/3174259 is merged. Let's change to "Partially fixes"

2024-07-23 12:20 UTC, terrakok commented
Maybe we can add the method to the library at the moment? And deprecate it when the platform implementation is merged

2024-07-24 07:11 UTC, MatkovIvan approved these changes

2024-07-26 10:41 UTC, igordmn approved these changes

2024-07-26 10:54 UTC, merged